### ISSUE TITLE
console not accessible

### ISSUE THREAD

**Issue by Chrawnus** [probable-basilisk/cheatgui#13]
Using GitHub Desktop to clone the repository, trying to access the console, even after adding bin/pollnet.dll to the cheatgui mod folder throws a `LUA: Gui error: [string "data/hax/console.lua"]:274: attempt to index local 'tdata' (a nil value)` error message, and the cheatgui UI disappears from the screen

**Comment by probable-basilisk** [comment]
That should be fixed with latest commit (https://github.com/probable-basilisk/cheatgui/commit/91eab90171b40efdf74fad42d71d5b6b71ff12bf); unfortunately I don't have access to a windows desktop at the moment and can't test.

**Comment by Chrawnus** [comment]
Seems to be fixed on my end, closing issue.
