### ISSUE TITLE
Am I missing a step?

### ISSUE THREAD

**Issue by MrDrunkinDragon** [probable-basilisk/cheatgui#2]
So I followed your directions (pretty easy)

Went to my steamapps\common\Noita
Created a mods directory..
then ran your git command...
When I open up Noita I don't see the option anywhere... Did I miss something, or is there only a special version of Noita that allows mods?

**Comment by MrDrunkinDragon** [comment]
Nevermind I'm derp... forgot to opt into beta on steam 🤦‍♂

**Comment by probable-basilisk** [comment]
Problem solved. :)
