### ISSUE TITLE
Pagination broken on certain resolutions

### ISSUE THREAD

**Issue by Dregu** [probable-basilisk/cheatgui#8]
Pagination arrow on spell list is unusable on certain resolution settings, because it's behind the spells. (internal_size_h="1080" 
  internal_size_w="1920")

**Comment by probable-basilisk** [comment]
@Dregu how are you setting the internal resolution? Pagination is fine at window resolution 1920x1080, virtual resolution 1920x1080:

![cheatgui_vres_1920_1080](https://user-images.githubusercontent.com/56415496/68163705-2326d400-ff29-11e9-90a2-f0ca05c8339f.jpg)

**Comment by probable-basilisk** [comment]
Should be fixed as of https://github.com/probable-basilisk/cheatgui/commit/0208d709544d29a43e5be09ab7a7965e9fb6916b.
